import mongoose from 'mongoose';

export const ADMIN_ROLE = 'SUPER ADMIN';
export const USER_ROLE = 'NORMAL USER';

export const INIT_PERMISSIONS = [
  // ================= MODULE: COMPANIES =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000001'),
    name: 'Create a company',
    apiPath: '/api/v1/companies',
    method: 'POST',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000002'),
    name: 'Fetch list company with paginate',
    apiPath: '/api/v1/companies',
    method: 'GET',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000003'),
    name: 'Fetch company by id',
    apiPath: '/api/v1/companies/:id',
    method: 'GET',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000004'),
    name: 'Update a company',
    apiPath: '/api/v1/companies/:id',
    method: 'PATCH',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000005'),
    name: 'Remove a company',
    apiPath: '/api/v1/companies/:id',
    method: 'DELETE',
    module: 'COMPANIES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },

  // ================= MODULE: AUTH =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000006'),
    name: 'User login',
    apiPath: '/api/v1/auth/login',
    method: 'POST',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000007'),
    name: 'Register a new user',
    apiPath: '/api/v1/auth/register',
    method: 'POST',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000008'),
    name: 'Get user information',
    apiPath: '/api/v1/auth/account',
    method: 'GET',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000009'),
    name: 'Get user by refresh token',
    apiPath: '/api/v1/auth/refresh',
    method: 'GET',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000000a'),
    name: 'User logout',
    apiPath: '/api/v1/auth/logout',
    method: 'POST',
    module: 'AUTH',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },

  // ================= MODULE: FILES =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000000b'),
    name: 'Upload single file',
    apiPath: '/api/v1/files/upload',
    method: 'POST',
    module: 'FILES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },

  // ================= MODULE: JOBS =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000000c'),
    name: 'Create a new job',
    apiPath: '/api/v1/jobs',
    method: 'POST',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000000d'),
    name: 'Fetch job with paginate',
    apiPath: '/api/v1/jobs',
    method: 'GET',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000000e'),
    name: 'Fetch job by id',
    apiPath: '/api/v1/jobs/:id',
    method: 'GET',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000000f'),
    name: 'Update a job',
    apiPath: '/api/v1/jobs/:id',
    method: 'PATCH',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000010'),
    name: 'Delete a job',
    apiPath: '/api/v1/jobs/:id',
    method: 'DELETE',
    module: 'JOBS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },

  // ================= MODULE: RESUMES =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000011'),
    name: 'Create a new resume',
    apiPath: '/api/v1/resumes',
    method: 'POST',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000012'),
    name: 'Fetch all resumes with paginate',
    apiPath: '/api/v1/resumes',
    method: 'GET',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000013'),
    name: 'Get resumes by user',
    apiPath: '/api/v1/resumes/by-user',
    method: 'POST',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000014'),
    name: 'Fetch a resume by id',
    apiPath: '/api/v1/resumes/:id',
    method: 'GET',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000015'),
    name: 'Update status resume',
    apiPath: '/api/v1/resumes/:id',
    method: 'PATCH',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000016'),
    name: 'Delete a resume by id',
    apiPath: '/api/v1/resumes/:id',
    method: 'DELETE',
    module: 'RESUMES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },

  // ================= MODULE: ROLES =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000017'),
    name: 'Create a new role',
    apiPath: '/api/v1/roles',
    method: 'POST',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000018'),
    name: 'Fetch roles with paginate',
    apiPath: '/api/v1/roles',
    method: 'GET',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000019'),
    name: 'Fetch a role by ID',
    apiPath: '/api/v1/roles/:id',
    method: 'GET',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000001a'),
    name: 'Update a role by ID',
    apiPath: '/api/v1/roles/:id',
    method: 'PATCH',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000001b'),
    name: 'Delete a role by ID',
    apiPath: '/api/v1/roles/:id',
    method: 'DELETE',
    module: 'ROLES',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },

  // ================= MODULE: USERS =================
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000001c'),
    name: 'Create a new User',
    apiPath: '/api/v1/users',
    method: 'POST',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000001d'),
    name: 'Fetch user with paginate',
    apiPath: '/api/v1/users',
    method: 'GET',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000001e'),
    name: 'Fetch user by id',
    apiPath: '/api/v1/users/:id',
    method: 'GET',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f60000001f'),
    name: 'Update a User',
    apiPath: '/api/v1/users',
    method: 'PATCH',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000020'),
    name: 'Delete a User',
    apiPath: '/api/v1/users/:id',
    method: 'DELETE',
    module: 'USERS',
    createdBy: {
      _id: new mongoose.Types.ObjectId('65d0a1b2c3d4e5f600000000'),
      email: 'admin@gmail.com',
    },
    updatedBy: null,
    deletedBy: null,
    isDeleted: false,
    deletedAt: null,
  },
];
